proyectoProgramaciónAvanzada/Controllers/EstudianteController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using proyectoProgramaciónAvanzada.Models;

namespace proyectoProgramaciónAvanzada.Controllers
{
    public class EstudianteController : Controller
    {
        private EnseñanzaVoluntariaEntities db = new EnseñanzaVoluntariaEntities();

        // GET: Estudiante
        [Authorize(Roles = "admin, estudiante, profesor")]
        public ActionResult Index()
        {
            return View();
        }

        [Authorize(Roles = "admin, estudiante, profesor")]
        public ActionResult Continentes()
        {
            return View("Estudios Sociales/Continentes");
        }

        [Authorize(Roles = "admin, estudiante, profesor")]
        public ActionResult Tectonismo()
        {
            return View("Estudios Sociales/Tectonismo");
        }

        [Authorize(Roles = "admin, estudiante, profesor")]
        public ActionResult HistoriaCR()
        {
            return View("Estudios Sociales/HistoriaCostaRica");
        }

        [Authorize(Roles = "admin, estudiante, profesor")]
        public ActionResult EstructuraOracion()
        {
            return View("Espaniol/EstructuraOracion");
        }

        [Authorize(Roles = "admin, estudiante, profesor")]
        public ActionResult UsoVyB()
        {
            return View("Espaniol/UsoVyB");
        }

        [Authorize(Roles = "admin, estudiante, profesor")]
        public ActionResult UsoSignosPuntuacion()
        {
            return View("Espaniol/UsoSignosPuntuacion");
        }

        [Authorize(Roles = "admin, estudiante, profesor")]
        public ActionResult Esqueleto()
        {
            return View("Ciencias/Esqueleto");
        }

        [Authorize(Roles = "admin, estudiante, profesor")]
        public ActionResult Celula()
        {
            return View("Ciencias/Celula");
        }

        [Authorize(Roles = "admin, estudiante, profesor")]
        public ActionResult SistemaDigestivo()
        {
            return View("Ciencias/SistemaDigestivo");
        }

        [Authorize(Roles = "admin, estudiante, profesor")]
        public ActionResult Multiplicacion()
        {
            return View("Matemáticas/Multiplicacion");
        }

        [Authorize(Roles = "admin, estudiante, profesor")]
        public ActionResult Resta()
        {
            return View("Matemáticas/Resta");
        }

        [Authorize(Roles = "admin, estudiante, profesor")]
        public ActionResult Suma()
        {
            return View("Matemáticas/Suma");
        }

        [Authorize(Roles = "admin, estudiante, profesor")]
        public ActionResult Archivos()
        {
            return View(db.MATERIAL_TUTORIA.ToList());
        }

        [Authorize(Roles = "admin, estudiante, profesor")]
        [HttpPost]
        public ActionResult Descargar(FormCollection valores)
        {
            var rutaArchivo = valores["RUTA"];

            var ruta = Server.MapPath(rutaArchivo);

            return File(ruta,"application/", rutaArchivo);
        }

        [Authorize(Roles = "admin, estudiante")]
        public ActionResult CalificaProfe()
        {
            ViewBag.Profesores = db.USUARIOS.Where(u => u.AspNetRoles.Name == "profesor").ToList();

            return View();
        }

        [HttpPost]
        [Authorize(Roles = "admin, estudiante")]
        public ActionResult CalificarProfesor(FormCollection valores)
        {
            var ID_PROFE = valores["ID_USUARIO"];
            var CALIFICACIONDADA = valores["CALIFICACION"];
            var ID_TUTORIA_CURSOS_PARAM = db.TUTORIA_CURSOS.Where(t => t.ID_PROFESOR == null).FirstOrDefault().ID_TUTORIA_CURSOS;
            ViewBag.Profesores = db.USUARIOS.Where(u => u.AspNetRoles.Name == "profesor").ToList();

            CALIFICACION_TUTORIA calif = new CALIFICACION_TUTORIA()
            {
                CALIFICACION = decimal.Parse(CALIFICACIONDADA),
                ID_TUTORIA_CURSOS = ID_TUTORIA_CURSOS_PARAM,
                ID_USUARIO = int.Parse(ID_PROFE)
            };

            try
            {
                db.CALIFICACION_TUTORIA.Add(calif);
                db.SaveChanges();
                ViewBag.exito = "Calificación enviada exitosamente.";
            }
            catch 
            {
                ViewBag.error = "Error al enviar la calificación.";
            }

            return View("CalificaProfe");
        }
    }
}

proyectoProgramaciónAvanzada/Views/Estudiante/Archivos.cshtml
@model IEnumerable<proyectoProgramaciónAvanzada.Models.MATERIAL_TUTORIA>

@{
    ViewBag.Title = "Archivos";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<section>
    <div class="container">
        <h2 style="text-align:center">Archivos de las tutorías</h2>

        @foreach (var item in Model)
        {
            <div class="container grey lighten-4" style="width: 30vw; padding: 15px; margin-bottom: 30px;">
                <div class="titulo">
                    <h4>@Html.DisplayTextFor(modelItem => item.TITULO_COMENTARIO)</h4>
                </div>
                <div class="contenido">
                    <p>
                        @Html.DisplayTextFor(modelItem => item.CUERPO_COMENTARIO)
                    </p>

                    <form action="/Estudiante/Descargar" method="post">
                        <input type="hidden" name="RUTA" readonly value="@Html.DisplayTextFor(modelItem => item.DIRECCION_ARCHIVO)" />
                        <input class="waves-effect waves-light btn" type="submit" value="Descargar Contenido" style="color: white;" />
                    </form>
                </div>
            </div>
        }
    </div>

</section>

proyectoProgramaciónAvanzada/Views/Estudiante/CalificaProfe.cshtml
@model proyectoProgramaciónAvanzada.Models.CALIFICACION_TUTORIA

@{
    ViewBag.Title = "CalificaProfe";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<section>
    <div class="container">
        <h2 style="text-align:center">Calificación Profesor</h2>

        <h4 style="color: green;">@ViewBag.exito</h4>
        <h4 style="color: red;">@ViewBag.error</h4>

        @using (Html.BeginForm())
        {
            @Html.AntiForgeryToken()

            <div class="form-horizontal">
                <hr />
                @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                <div class="form-group">
                    @Html.Label("Profesores", htmlAttributes: new { @class = "control-label col-md-2" })
                    <div>
                        @{
                            List<SelectListItem> profesores = new List<SelectListItem>();
                            foreach (var profesor in ViewBag.Profesores)
                            {
                                var nombreCompleto = profesor.NOMBRE + " " + profesor.APELLIDO1 + " " + profesor.APELLIDO2;
                                var id = profesor.ID_USUARIO.ToString();
                                profesores.Add(new SelectListItem
                                {
                                    Text = nombreCompleto,
                                    Value = id
                                });
                            }
                        }
                        @Html.DropDownListFor(model => model.ID_USUARIO, profesores, htmlAttributes: new { @class = "form-control", @style = "display: block;" })
                    </div>
                </div>

                <div class="form-group">
                    @Html.Label("Calificación:", htmlAttributes: new { @class = "control-label col-md-2" })
                    <p class="range-field">
                        <input type="range" name="CALIFICACION" id="test5" min="0" max="5" />
                    </p>
                </div>

                <div class="form-group">
                    <div class="col-md-offset-2 col-md-10">
                        @Html.ActionLink("Volver", "Index", "Estudiante", null, new { @class = "waves-effect waves-light btn-small" })
                        <input type="submit" value="Calificar" class="btn btn-small" />
                    </div>
                </div>
            </div>
        }
        </div>
</section>

proyectoProgramaciónAvanzada/Views/Estudiante/Index.cshtml
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<section>

    <div class="black white-text center">
        <div class="black container">
            <br />
        </div>
        <div class="container">
            <div class="Section">
                <h3>Estudios Sociales</h3>
                <p>
                    En esta sección podrá encontrar material relacionado a la materia de Estudios
                    Sociales, a continuación se le presentan los siguientes temas disponibles para que
                    puedas estudiarlos:
                </p>
                <div class="Section">
                    @Html.ActionLink("Continentes", "Continentes", "Estudiante", null, new { @class = "waves-effect waves-light btn" })
                    @Html.ActionLink("Tectonismo", "Tectonismo", "Estudiante", null, new { @class = "waves-effect waves-light btn" })
                    @Html.ActionLink("Historia de Costa Rica", "HistoriaCR", "Estudiante", null, new { @class = "waves-effect waves-light btn" })
                    <div class="container">
                        <br />
                    </div>
                </div>
            </div>
        </div>
    </div>

    <div class="parallax-container">
        <div class="parallax">
            <img src="../Imagenes/coliseo-romano-wallpaper-hd.jpg" alt="" />
        </div>
    </div>

    <div class="black white-text center">
        <div class="black container">
            <br />
        </div>
        <div class="container">
            <div class="Section">
                <h3>Español</h3>
                <p>
                    En esta sección podrá encontrar material relacionado a la materia de Español
                    , a continuación se le presentan los siguientes temas disponibles para que
                    puedas estudiarlos:
                </p>
                <div class="Section">
                    @Html.ActionLink("Uso de los Signos de Puntuación", "UsoSignosPuntuacion", "Estudiante", null, new { @class = "waves-effect waves-light btn orange darken-1" })
                    @Html.ActionLink("Uso de la V y la B", "UsoVyB", "Estudiante", null, new { @class = "waves-effect waves-light btn orange darken-1" })
                    @Html.ActionLink("Estructura de la Oración", "EstructuraOracion", "Estudiante", null, new { @class = "waves-effect waves-light btn orange darken-1" })
                    <div class="container">
                        <br />
                    </div>
                </div>
            </div>
        </div>
    </div>

    <div class="parallax-container">
        <div class="parallax">
            <img src="../Imagenes/biblioteca_libros_prohibidos.jpg" alt="" />
        </div>
    </div>

    <div class="black white-text center">
        <div class="black container">
            <br />
        </div>
        <div class="container">
            <div class="Section">
                <h3>Ciencias</h3>
                <p>
                    En esta sección podrá encontrar material relacionado a la materia de Ciencias
                    , a continuación se le presentan los siguientes temas disponibles para que
                    puedas estudiarlos:
                </p>
                <div class="Section">
                    @Html.ActionLink("Sistema Digestivo", "SistemaDigestivo", "Estudiante", null, new { @class = "waves-effect waves-light btn green darken-1" })
                    @Html.ActionLink("Esqueleto Humano", "Esqueleto", "Estudiante", null, new { @class = "waves-effect waves-light btn green darken-1" })
                    @Html.ActionLink("La Célula", "Celula", "Estudiante", null, new { @class = "waves-effect waves-light btn green darken-1" })
                    <div class="container">
                        <br />
                    </div>
                </div>
            </div>
        </div>
    </div>

    <div class="parallax-container">
        <div class="parallax">
            <img src="../Imagenes/quimica1.jpg" alt="" />
        </div>
    </div>

    <div class="black white-text center">
        <div class="black container">
            <br />
        </div>
        <div class="container">
            <div class="Section">
                <h3>Matemáticas</h3>
                <p>
                    En esta sección podrá encontrar material relacionado a la materia de Matemáticas
                    , a continuación se le presentan los siguientes temas disponibles para que
                    puedas estudiarlos:
                </p>
                <div class="Section">
                    @Html.ActionLink("Suma", "Suma", "Estudiante", null, new { @class = "waves-effect waves-light btn deep-orange darken-3" })
                    @Html.ActionLink("Resta", "Resta", "Estudiante", null, new { @class = "waves-effect waves-light btn deep-orange darken-3" })
                    @Html.ActionLink("Multiplicación", "Multiplicacion", "Estudiante", null, new { @class = "waves-effect waves-light btn deep-orange darken-3" })
                    <div class="container">
                        <br />
                    </div>
                </div>
            </div>
        </div>
    </div>
    <div class="parallax-container">
        <div class="parallax">
            <img src="../Imagenes/matematicas.jpg" alt="" />
        </div>
    </div>

    <script>
        document.addEventListener('DOMContentLoaded', function () {
            M.AutoInit();
        });
    </script>
    </section>